# Configuration file for CircleCI 2.0.
version: 2
jobs:
  # Main build job.
  build:
    working_directory: ~/flame_ws
    docker:
      # Only need kinetic image so that we can easily use OpenCV 3.3.
      - image: osrf/ros:kinetic-desktop-full
    steps:
      # Commands to checkout/build repo.
      - checkout:
          path: ~/flame_ws/src/flame_ros

      # Install dependencies via apt/ros-dep.
      - run: apt-get install -y libboost-all-dev libpcl-dev python-catkin-tools
      - run: cd src && git clone git@github.com:robustrobotics/flame.git
      - run: source /opt/ros/kinetic/setup.sh && catkin init
      - run: source /opt/ros/kinetic/setup.sh && rosdep install -iy --from-paths ./src

      # Install dependencies from source.
      - run: mkdir -p ./dependencies/src
      - run: ./src/flame/scripts/eigen.sh ./dependencies/src ./dependencies
      - run: ./src/flame/scripts/sophus.sh ./dependencies/src ./dependencies
      - run: cp ./src/flame/scripts/env.sh ./dependencies

      # Build!
      - run: source /opt/ros/kinetic/setup.sh && source ./dependencies/env.sh && catkin build

# Two main workflows: One run per commit, one to run master nightly.
workflows:
  version: 2
  commit-workflow:
    jobs:
      - build
  nightly-workflow:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only: master
    jobs:
      - build
